plugins { id 'com.android.application' }

android {
    namespace 'ec.edu.matematicasvszombis'
    compileSdk 35

    defaultConfig {
        applicationId 'ec.edu.matematicasvszombis.estudiante'
        minSdk 23
        targetSdk 35
        versionCode 40100
        versionName '4.1.0'
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
