import 'dart:math';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
void main()=>runApp(const App());
class App extends StatelessWidget{const App({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Matemáticas vs. Zombis',theme:ThemeData(brightness:Brightness.dark,colorSchemeSeed:const Color(0xffb8f34b),useMaterial3:true),home:const Game());}
class Q{final String topic,text,answer,hint;final List<String> options;const Q(this.topic,this.text,this.options,this.answer,this.hint);}
List<Q> buildBank(){
 final list=<Q>[];
 for(var i=1;i<=10;i++){final a=4+i*2,b=2+i,ans=a+b;list.add(Q('Enteros','Exploración '+i.toString()+': calcula '+a.toString()+' + '+b.toString()+'.',[ans.toString(),(ans+2).toString(),(ans-3).toString(),(a*b).toString()],ans.toString(),'Suma primero las unidades y luego las decenas.'));}
 for(var i=1;i<=5;i++){final d=5+i,a=1+i,b=2,ans=a+b;list.add(Q('Fracciones','Reto '+i.toString()+': calcula '+a.toString()+'/'+d.toString()+' + '+b.toString()+'/'+d.toString()+'.',[ans.toString()+'/'+d.toString(),(ans+1).toString()+'/'+d.toString(),ans.toString()+'/'+(d+1).toString(),(a*b).toString()+'/'+d.toString()],ans.toString()+'/'+d.toString(),'Los denominadores son iguales: suma solo los numeradores.'));}
 for(var i=1;i<=5;i++){final a=i+1,b=i/10,ans=a+b;final correct=ans.toStringAsFixed(1).replaceAll('.',',');list.add(Q('Decimales','Reto '+(i+5).toString()+': calcula '+a.toString()+' + '+b.toStringAsFixed(1).replaceAll('.',',')+'.',[correct,(ans+1).toStringAsFixed(1).replaceAll('.',','),(ans-.2).toStringAsFixed(1).replaceAll('.',','),(a*b).toStringAsFixed(1).replaceAll('.',',')],correct,'Alinea las comas decimales antes de sumar.'));}
 for(var i=1;i<=5;i++){final base=i+1,ans=base*base;list.add(Q('Potencias','Reto '+i.toString()+': ¿cuánto es '+base.toString()+'²?',[ans.toString(),(ans+base).toString(),(base*2).toString(),(ans-1).toString()],ans.toString(),'Elevar al cuadrado significa multiplicar el número por sí mismo.'));}
 for(var i=1;i<=5;i++){final root=i+5,sq=root*root;list.add(Q('Raíces','Reto '+(i+5).toString()+': ¿cuál es √'+sq.toString()+'?',[root.toString(),(root+1).toString(),(root-2).toString(),(sq~/2).toString()],root.toString(),'Busca el número que multiplicado por sí mismo produce el radicando.'));}
 for(var i=1;i<=5;i++){final x=i+2,c=i+3,result=2*x+c;list.add(Q('Ecuaciones','Reto '+i.toString()+': resuelve 2x + '+c.toString()+' = '+result.toString()+'.',['x = '+x.toString(),'x = '+(x+2).toString(),'x = '+(result-c).toString(),'x = '+(x-1).toString()],'x = '+x.toString(),'Resta '+c.toString()+' en ambos miembros y divide para 2.'));}
 for(var i=1;i<=5;i++){final a=i+2,b=i+1;list.add(Q('Álgebra','Reto '+(i+5).toString()+': reduce '+a.toString()+'x + '+b.toString()+'x + 4.',[''+(a+b).toString()+'x + 4',''+(a*b).toString()+'x + 4',''+(a+b+4).toString()+'x',''+(a-b).toString()+'x + 4'],(a+b).toString()+'x + 4','Suma los coeficientes de los términos que tienen x; conserva el término independiente.'));}
 for(var i=1;i<=5;i++){final unit=i+2,n=i+4,total=unit*n;list.add(Q('Proporcionalidad','Reto '+i.toString()+': cada paquete cuesta \$'+unit.toString()+'. ¿Cuánto cuestan '+n.toString()+'?',['\$'+total.toString(),'\$'+(total+unit).toString(),'\$'+(unit+n).toString(),'\$'+(total-unit).toString()],'\$'+total.toString(),'Multiplica el precio unitario por la cantidad de paquetes.'));}
 for(var i=1;i<=5;i++){final price=20+i*10,percent=10,discount=price~/10,finalPrice=price-discount;list.add(Q('Porcentajes','Reto '+(i+5).toString()+': un artículo de \$'+price.toString()+' tiene 10 % de descuento. Precio final:',['\$'+finalPrice.toString(),'\$'+discount.toString(),'\$'+(price+discount).toString(),'\$'+(finalPrice-5).toString()],'\$'+finalPrice.toString(),'El 10 % es la décima parte. Calcula el descuento y réstalo del precio.'));}
 for(var i=1;i<=4;i++){final base=4+i*2,height=3+i,area=base*height~/2;list.add(Q('Geometría','Reto '+i.toString()+': área de un triángulo de base '+base.toString()+' cm y altura '+height.toString()+' cm.',[''+area.toString()+' cm²',''+(base*height).toString()+' cm²',''+(base+height).toString()+' cm²',''+(area+2).toString()+' cm²'],area.toString()+' cm²','Multiplica base por altura y divide el resultado para 2.'));}
 for(var i=1;i<=3;i++){final a=4+i,b=2+i,c=2,volume=a*b*c;list.add(Q('Volumen','Reto '+(i+4).toString()+': volumen de un prisma '+a.toString()+' × '+b.toString()+' × 2 m.',[''+volume.toString()+' m³',''+(a*b).toString()+' m³',''+(a+b+c).toString()+' m³',''+(volume+4).toString()+' m³'],volume.toString()+' m³','Multiplica largo, ancho y altura.'));}
 for(var i=1;i<=3;i++){final center=4+i;list.add(Q(i<3?'Estadística':'Probabilidad',i<3?'Reto '+(i+7).toString()+': media de '+(center-2).toString()+', '+center.toString()+' y '+(center+2).toString()+'.':'Reto 10: hay 3 fichas verdes y 7 rojas. P(verde):',i<3?[center.toString(),(center+1).toString(),(center*3).toString(),(center-1).toString()]:['3/10','7/10','3/7','1/3'],i<3?center.toString():'3/10',i<3?'Suma los tres datos y divide para 3.':'Casos favorables sobre casos totales: 3 de 10.'));}
 return list;
}
final bank=buildBank();
class Defender{final int row,col;int hp=3;Defender(this.row,this.col);}
class Enemy{int row,hp=3;double col;Enemy(this.row,this.col);}
class Game extends StatefulWidget{const Game({super.key});@override State<Game> createState()=>_GameState();}
class _GameState extends State<Game>{
 final rnd=Random(),defs=<Defender>[],foes=<Enemy>[];int mission=0,wave=1,energy=100,score=0,lives=5,qi=0,shotRow=2,shotPulse=0;bool started=false,paused=false,won=false,alarmOn=false;String msg='',errorDetail='';
 static const missions=['Isla Verde','Desierto Racional','Volcán de Potencias','Glaciar Algebraico','Ciudad Proporcional','Fortaleza Matemática'];
 Q get q=>bank[qi%bank.length];
 String get objective=>['Resuelve 10 operaciones con enteros y gana confianza.','Supera 10 retos de fracciones y decimales.','Domina 10 potencias y raíces antes de llegar al cráter.','Resuelve 10 expresiones y ecuaciones para cruzar el glaciar.','Aplica proporcionalidad y porcentajes en 10 decisiones.','Integra geometría, volumen, estadística y probabilidad en 10 retos finales.'][min(mission,5)];
 bool get inDanger=>foes.any((e)=>e.col<1.6);
 void start()=>setState((){started=true;won=false;alarmOn=false;mission=0;wave=1;energy=100;score=0;lives=5;qi=0;shotPulse=0;msg='';errorDetail='';defs.clear();foes.clear();spawn(2);});
 void spawn(int n){for(var i=0;i<n;i++)foes.add(Enemy(rnd.nextInt(5),6+rnd.nextDouble()));}
 void place(int r,int c){if(paused||energy<50||c>4||defs.any((d)=>d.row==r&&d.col==c))return;setState((){energy-=50;defs.add(Defender(r,c));msg='Defensa lógica desplegada';});}
 double? valueOf(String s){final fraction=RegExp(r'(-?\d+)\s*/\s*(-?\d+)').firstMatch(s);if(fraction!=null){final b=double.parse(fraction.group(2)!);return b==0?null:double.parse(fraction.group(1)!)/b;}final m=RegExp(r'-?\d+(?:[\.,]\d+)?').firstMatch(s);return m==null?null:double.tryParse(m.group(0)!.replaceAll(',','.'));}
 int errorLevel(String chosen,String correct){final a=valueOf(chosen),b=valueOf(correct);if(a==null||b==null)return 2;final distance=(a-b).abs()/max(b.abs(),1);if(distance<=.25)return 1;if(distance<=1)return 2;return 3;}
 void answer(String v){if(paused)return;final current=q;setState((){final ok=v==current.answer,oldMission=mission;if(ok){energy=min(200,energy+35);score+=15;errorDetail='';if(foes.isNotEmpty){final closest=foes.reduce((a,b)=>a.col<b.col?a:b);shotRow=closest.row;shotPulse++;foes.remove(closest);msg='¡Impacto correcto! El proyectil eliminó al zombi objetivo.';}else{msg='¡Correcto! +35 de energía';}}else{final amount=errorLevel(v,current.answer);spawn(amount);msg=amount==1?'Error cercano: apareció 1 zombi.':amount==2?'Respuesta muy alejada: aparecieron 2 zombis.':'Respuesta sin relación: aparecieron 3 zombis.';errorDetail='Tu respuesta: '+v+'\nRespuesta correcta: '+current.answer+'\nConsecuencia: aparecieron '+amount.toString()+(amount==1?' zombi.':' zombis.')+'\nProcedimiento: '+current.hint;}for(final e in foes)e.col-=ok ? 0.18 : 0.65;for(final e in List<Enemy>.from(foes)){final hits=defs.where((d)=>d.row==e.row&&(d.col-e.col).abs()<.7).toList();if(hits.isNotEmpty){hits.first.hp--;e.hp--;if(hits.first.hp<=0)defs.remove(hits.first);}if(e.col<0){foes.remove(e);lives--;}}qi++;if(qi>=bank.length){won=true;return;}mission=qi~/10;wave=((qi%10)~/3)+1;if(mission!=oldMission){energy=min(200,energy+80);defs.clear();foes.clear();spawn(2+mission);msg='¡Isla liberada! Comienza '+missions[mission]+'.';}else if(foes.isEmpty){spawn(1+min(wave,3));}if(lives<=0){started=false;msg='La ciudad necesita otra estrategia';}if(inDanger&&!alarmOn){alarmOn=true;SystemSound.play(SystemSoundType.alert);HapticFeedback.heavyImpact();}else if(!inDanger){alarmOn=false;}});}
 @override Widget build(BuildContext c){if(!started)return Start(onStart:start,msg:msg);if(won)return Victory(score:score,onRestart:start);return Scaffold(backgroundColor:const Color(0xff07110c),body:SafeArea(child:LayoutBuilder(builder:(c,s){final wide=s.maxWidth>760;return Column(children:[Bar(mission:mission,wave:wave,exercise:(qi%10)+1,energy:energy,score:score,lives:lives,paused:paused,onPause:()=>setState(()=>paused=!paused)),MissionAlert(objective:objective,danger:inDanger),Expanded(child:wide?Row(children:[Expanded(child:Field(defs:defs,foes:foes,onCell:place,mission:mission,shotRow:shotRow,shotPulse:shotPulse)),SizedBox(width:390,child:Quiz(q:q,onAnswer:answer,msg:msg,errorDetail:errorDetail))]):Column(children:[Expanded(child:Field(defs:defs,foes:foes,onCell:place,mission:mission,shotRow:shotRow,shotPulse:shotPulse)),SizedBox(height:390,child:Quiz(q:q,onAnswer:answer,msg:msg,errorDetail:errorDetail))]))]);})));}
}
class Start extends StatelessWidget{final VoidCallback onStart;final String msg;const Start({super.key,required this.onStart,required this.msg});@override Widget build(BuildContext c)=>Scaffold(body:Container(decoration:const BoxDecoration(gradient:RadialGradient(center:Alignment.topCenter,radius:1.2,colors:[Color(0xff31562b),Color(0xff07110c)])),child:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[Container(width:105,height:105,decoration:BoxDecoration(color:const Color(0xffb8f34b),borderRadius:BorderRadius.circular(28)),child:const Center(child:Text('Σ',style:TextStyle(fontSize:62,fontWeight:FontWeight.w900,color:Color(0xff102018))))),const SizedBox(height:20),const Text('MATEMÁTICAS',style:TextStyle(fontSize:42,fontWeight:FontWeight.w900)),const Text('VS. ZOMBIS',style:TextStyle(fontSize:42,fontWeight:FontWeight.w900,color:Color(0xffb8f34b))),const SizedBox(height:14),const SizedBox(width:600,child:Text('Recorre seis islas de aprendizaje. En cada paisaje resolverás 10 ejercicios, ganarás confianza y ayudarás al Guardián Sigma a defender su base.',textAlign:TextAlign.center,style:TextStyle(fontSize:18,height:1.5))),const SizedBox(height:24),FilledButton.icon(style:FilledButton.styleFrom(backgroundColor:const Color(0xffb8f34b),foregroundColor:const Color(0xff102018),padding:const EdgeInsets.all(20)),onPressed:onStart,icon:const Icon(Icons.play_arrow),label:const Text('INICIAR CAMPAÑA',style:TextStyle(fontWeight:FontWeight.w900))),if(msg.isNotEmpty)Padding(padding:const EdgeInsets.all(14),child:Text(msg)),const Wrap(spacing:10,children:[Chip(label:Text('6 islas')),Chip(label:Text('60 ejercicios')),Chip(label:Text('Sin internet')),Chip(label:Text('Dificultad ascendente'))])])))));}
class Bar extends StatelessWidget{final int mission,wave,exercise,energy,score,lives;final bool paused;final VoidCallback onPause;const Bar({super.key,required this.mission,required this.wave,required this.exercise,required this.energy,required this.score,required this.lives,required this.paused,required this.onPause});@override Widget build(BuildContext c)=>Container(height:70,padding:const EdgeInsets.symmetric(horizontal:14),color:const Color(0xff0d1d14),child:Row(children:[Expanded(child:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.start,children:[Text('ISLA '+(mission+1).toString()+' DE 6 · EJERCICIO '+exercise.toString()+' DE 10',style:const TextStyle(fontSize:11,color:Color(0xff9bb09f))),Text(_GameState.missions[min(mission,5)],style:const TextStyle(fontWeight:FontWeight.w800))])),Stat(Icons.bolt,energy,const Color(0xffffd45c)),Stat(Icons.favorite,lives,const Color(0xffff6b62)),Stat(Icons.stars,score,const Color(0xffb8f34b)),IconButton(onPressed:onPause,icon:Icon(paused?Icons.play_arrow:Icons.pause))]));}
class Stat extends StatelessWidget{final IconData icon;final int n;final Color color;const Stat(this.icon,this.n,this.color,{super.key});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.symmetric(horizontal:6),child:Row(children:[Icon(icon,color:color,size:19),Text(n.toString(),style:const TextStyle(fontWeight:FontWeight.w900))]));}
class MissionAlert extends StatelessWidget{final String objective;final bool danger;const MissionAlert({super.key,required this.objective,required this.danger});@override Widget build(BuildContext c)=>AnimatedContainer(duration:const Duration(milliseconds:250),width:double.infinity,padding:const EdgeInsets.symmetric(horizontal:16,vertical:9),color:danger?const Color(0xff8b1717):const Color(0xff173220),child:Row(children:[Icon(danger?Icons.warning_amber_rounded:Icons.flag,color:danger?Colors.white:const Color(0xffb8f34b)),const SizedBox(width:10),Expanded(child:Text(danger?'¡ALARMA! Un zombi está cerca de la base. Responde correctamente y refuerza ese carril.':'OBJETIVO: '+objective,style:TextStyle(fontWeight:FontWeight.w800,fontSize:13,color:danger?Colors.white:const Color(0xffe5f4e8))))]));}
class Field extends StatelessWidget{
 final List<Defender> defs;final List<Enemy> foes;final void Function(int,int) onCell;final int mission,shotRow,shotPulse;
 const Field({super.key,required this.defs,required this.foes,required this.onCell,required this.mission,required this.shotRow,required this.shotPulse});
 @override Widget build(BuildContext c){
  const colors=[[Color(0xff55a94b),Color(0xff174c32)],[Color(0xffc8944c),Color(0xff563923)],[Color(0xffa63020),Color(0xff291015)],[Color(0xff70b8d0),Color(0xff183a55)],[Color(0xff7b54bd),Color(0xff20204d)],[Color(0xff34445f),Color(0xff111827)]];
  const scenery=['🌴  🏝️  🌊','🏜️  🌵  ☀️','🌋  🔥  🪨','❄️  🏔️  🌨️','🏙️  🌉  🚦','🏰  🌌  ✨'];
  final grid=Column(children:List.generate(5,(r)=>Expanded(child:Row(children:List.generate(7,(col)=>Expanded(child:InkWell(onTap:()=>onCell(r,col),child:Container(decoration:BoxDecoration(color:(r+col).isEven?const Color(0x1839a84a):const Color(0x181f7c37),border:Border.all(color:const Color(0x183fffff))),child:Center(child:Text(col<5?'+':'',style:const TextStyle(color:Color(0x5579d936),fontSize:24)))))))))));
  final defenseViews=defs.map((d)=>Align(alignment:Alignment(-1+(d.col+.5)*2/7,-1+(d.row+.5)*2/5),child:FractionallySizedBox(widthFactor:1/7,heightFactor:1/5,child:Container(margin:const EdgeInsets.all(4),decoration:BoxDecoration(color:const Color(0xffb8f34b),borderRadius:BorderRadius.circular(13)),child:const Icon(Icons.calculate,color:Color(0xff102018),size:32)))));
  final closest=foes.isEmpty?null:foes.reduce((a,b)=>a.col<b.col?a:b);
  final enemyViews=foes.map((e)=>Align(alignment:Alignment(-1+(e.col+.5)*2/7,-1+(e.row+.5)*2/5),child:FractionallySizedBox(widthFactor:1/7,heightFactor:1/5,child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(identical(e,closest)?'🎯':'',style:const TextStyle(fontSize:14)),const Text('🧟',style:TextStyle(fontSize:34)),Text('❤'+e.hp.toString(),style:const TextStyle(fontSize:10,color:Color(0xffffdddd)))]))));
  final hero=Align(alignment:Alignment(-.93,-1+(shotRow+.5)*2/5),child:const Text('🧙‍♂️',style:TextStyle(fontSize:40)));
  final projectile=shotPulse==0?const SizedBox.shrink():TweenAnimationBuilder<double>(key:ValueKey(shotPulse),tween:Tween(begin:-.78,end:.72),duration:const Duration(milliseconds:550),builder:(c,x,child)=>Align(alignment:Alignment(x,-1+(shotRow+.5)*2/5),child:const Text('⚡',style:TextStyle(fontSize:28))));
  return Container(margin:const EdgeInsets.all(12),decoration:BoxDecoration(borderRadius:BorderRadius.circular(18),gradient:LinearGradient(begin:Alignment.topCenter,end:Alignment.bottomCenter,colors:colors[min(mission,5)]),border:Border.all(color:const Color(0xffd6f0bb),width:2)),clipBehavior:Clip.antiAlias,child:Stack(children:[Positioned(right:12,top:8,child:Text(scenery[min(mission,5)],style:const TextStyle(fontSize:28))),grid,...defenseViews,...enemyViews,hero,projectile]));
 }
}
class Quiz extends StatefulWidget{final Q q;final void Function(String) onAnswer;final String msg,errorDetail;const Quiz({super.key,required this.q,required this.onAnswer,required this.msg,required this.errorDetail});@override State<Quiz> createState()=>_QuizState();}
class _QuizState extends State<Quiz>{bool hint=false;@override void didUpdateWidget(covariant Quiz old){super.didUpdateWidget(old);if(old.q!=widget.q)hint=false;}@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(15),color:const Color(0xff0c1912),child:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Chip(backgroundColor:const Color(0xffb8f34b),label:Text(widget.q.topic,style:const TextStyle(color:Color(0xff102018),fontWeight:FontWeight.w900))),const Spacer(),TextButton.icon(onPressed:()=>setState(()=>hint=!hint),icon:const Icon(Icons.school,color:Color(0xffffd45c)),label:const Text('AYUDA'))]),const SizedBox(height:6),Text(widget.q.text,style:const TextStyle(fontSize:19,fontWeight:FontWeight.w800,height:1.3)),if(hint)Container(width:double.infinity,margin:const EdgeInsets.only(top:10),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:const Color(0xff293718),border:Border.all(color:const Color(0xffffd45c)),borderRadius:BorderRadius.circular(10)),child:Text('GUÍA ESTRATÉGICA\n'+widget.q.hint+'\nPiensa el procedimiento antes de elegir; no respondas al azar.',style:const TextStyle(height:1.45))),const SizedBox(height:12),GridView.count(crossAxisCount:2,mainAxisSpacing:8,crossAxisSpacing:8,childAspectRatio:2.4,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),children:widget.q.options.map((x)=>OutlinedButton(onPressed:()=>widget.onAnswer(x),child:Text(x,style:const TextStyle(fontWeight:FontWeight.w800)))).toList()),if(widget.errorDetail.isNotEmpty)Container(width:double.infinity,margin:const EdgeInsets.only(top:12),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:const Color(0xff4b1f1f),border:Border.all(color:const Color(0xffff6b62)),borderRadius:BorderRadius.circular(10)),child:Text('ERROR EN LA RESOLUCIÓN\n'+widget.errorDetail,style:const TextStyle(fontSize:13,height:1.5,color:Color(0xffffdddd),fontWeight:FontWeight.w700))),if(widget.msg.isNotEmpty&&widget.errorDetail.isEmpty)Container(width:double.infinity,margin:const EdgeInsets.only(top:10),padding:const EdgeInsets.all(9),color:const Color(0xff1b3022),child:Text(widget.msg,style:const TextStyle(fontSize:12))) ])));}
class Victory extends StatelessWidget{final int score;final VoidCallback onRestart;const Victory({super.key,required this.score,required this.onRestart});@override Widget build(BuildContext c)=>Scaffold(body:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('🏆',style:TextStyle(fontSize:84)),const Text('¡RIOBAMBA ESTÁ A SALVO!',style:TextStyle(fontSize:32,fontWeight:FontWeight.w900,color:Color(0xffb8f34b))),Text(score.toString()+' puntos estratégicos'),const SizedBox(height:22),FilledButton(onPressed:onRestart,child:const Text('Jugar nuevamente'))])));}
