import 'dart:math';
import 'package:flutter/material.dart';
void main()=>runApp(const App());
class App extends StatelessWidget{const App({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Matemáticas vs. Zombis',theme:ThemeData(brightness:Brightness.dark,colorSchemeSeed:const Color(0xffb8f34b),useMaterial3:true),home:const Game());}
class Q{final String topic,text,answer,hint;final List<String> options;const Q(this.topic,this.text,this.options,this.answer,this.hint);}
const bank=<Q>[
 Q('Enteros','La temperatura era −6 °C y aumentó 14 °C. ¿Temperatura final?',['8 °C','−20 °C','20 °C','−8 °C'],'8 °C','Avanza 14 posiciones desde −6.'),
 Q('Racionales','Calcula 5/6 − 1/4.',['7/12','4/2','1/2','3/10'],'7/12','Usa denominador común 12.'),
 Q('Potencias','Simplifica 3² · 3⁴.',['3⁶','9⁸','3⁸','6⁶'],'3⁶','Con igual base, suma exponentes.'),
 Q('Raíces','¿Cuál es √225?',['15','25','13','112,5'],'15','Busca el número cuyo cuadrado es 225.'),
 Q('Notación científica','Expresa 0,00072 en notación científica.',['7,2 × 10⁻⁴','72 × 10⁻⁴','7,2 × 10⁴','0,72 × 10⁻⁴'],'7,2 × 10⁻⁴','Mueve la coma 4 lugares.'),
 Q('Álgebra','Reduce: 7x + 4 − 3x + 8.',['4x + 12','10x + 12','4x − 4','10x − 4'],'4x + 12','Agrupa términos semejantes.'),
 Q('Ecuaciones','Resuelve 4x − 7 = 21.',['x = 7','x = 14','x = 3,5','x = 28'],'x = 7','Suma 7 y divide para 4.'),
 Q('Proporcionalidad','5 cuadernos cuestan \$15. ¿Cuánto cuestan 8?',['\$24','\$18','\$40','\$23'],'\$24','Calcula primero el precio unitario.'),
 Q('Porcentajes','Una chaqueta de \$60 tiene 20 % de descuento.',['\$48','\$40','\$12','\$52'],'\$48','Resta a 60 el 20 % de 60.'),
 Q('Geometría','Área de trapecio: bases 10 y 6 cm, altura 5 cm.',['40 cm²','80 cm²','30 cm²','21 cm²'],'40 cm²','Suma bases, multiplica por altura y divide para 2.'),
 Q('Volumen','Volumen de un prisma de 6 m × 3 m × 2 m.',['36 m³','18 m³','11 m³','22 m³'],'36 m³','Multiplica las tres dimensiones.'),
 Q('Estadística','Media de 5, 7, 9, 11 y 13.',['9','8','10','45'],'9','Suma y divide para 5.'),
 Q('Probabilidad','Hay 4 fichas verdes y 6 amarillas. P(verde):',['2/5','3/5','4/6','1/4'],'2/5','Favorables sobre total: 4/10.'),
 Q('Polígonos','Suma de ángulos interiores de un octágono.',['1080°','720°','1440°','900°'],'1080°','Aplica (n − 2) × 180°.'),
 Q('Funciones','Si y = 2x + 3, ¿cuánto vale y cuando x = 4?',['11','9','8','14'],'11','Sustituye x por 4.')
];
class Defender{final int row,col;int hp=3;Defender(this.row,this.col);}
class Enemy{int row,hp=3;double col;Enemy(this.row,this.col);}
class Game extends StatefulWidget{const Game({super.key});@override State<Game> createState()=>_GameState();}
class _GameState extends State<Game>{
 final rnd=Random(),defs=<Defender>[],foes=<Enemy>[];int mission=0,wave=1,energy=100,score=0,lives=5,qi=0;bool started=false,paused=false,won=false;String msg='';
 static const missions=['Barrio de los Enteros','Laboratorio Algebraico','Fortaleza Geométrica','Central Estadística','Cumbre del Chimborazo'];
 Q get q=>bank[qi%bank.length];
 void start()=>setState((){started=true;won=false;mission=0;wave=1;energy=100;score=0;lives=5;qi=0;defs.clear();foes.clear();spawn(2);});
 void spawn(int n){for(var i=0;i<n;i++)foes.add(Enemy(rnd.nextInt(5),6+rnd.nextDouble()));}
 void place(int r,int c){if(paused||energy<50||c>4||defs.any((d)=>d.row==r&&d.col==c))return;setState((){energy-=50;defs.add(Defender(r,c));msg='Defensa lógica desplegada';});}
 void answer(String v){if(paused)return;setState((){final ok=v==q.answer;if(ok){energy=min(200,energy+35);score+=10;msg='¡Correcto! +35 de energía';for(final e in foes){if(defs.any((d)=>d.row==e.row))e.hp-=2;}foes.removeWhere((e)=>e.hp<=0);}else{msg='Pista: '+q.hint;lives--;}for(final e in foes)e.col-=ok ? 0.55 : 1.0;for(final e in List<Enemy>.from(foes)){final hits=defs.where((d)=>d.row==e.row&&(d.col-e.col).abs()<.7).toList();if(hits.isNotEmpty){hits.first.hp--;e.hp--;if(hits.first.hp<=0)defs.remove(hits.first);}if(e.col<0){foes.remove(e);lives--;}}qi++;if(foes.isEmpty){wave++;if(wave>3){mission++;wave=1;energy=min(200,energy+70);if(mission>=missions.length){won=true;return;}}spawn(1+wave+mission);}if(lives<=0){started=false;msg='La ciudad necesita otra estrategia';}});}
 @override Widget build(BuildContext c){if(!started)return Start(onStart:start,msg:msg);if(won)return Victory(score:score,onRestart:start);return Scaffold(backgroundColor:const Color(0xff07110c),body:SafeArea(child:LayoutBuilder(builder:(c,s){final wide=s.maxWidth>760;return Column(children:[Bar(mission:mission,wave:wave,energy:energy,score:score,lives:lives,paused:paused,onPause:()=>setState(()=>paused=!paused)),Expanded(child:wide?Row(children:[Expanded(child:Field(defs:defs,foes:foes,onCell:place)),SizedBox(width:370,child:Quiz(q:q,onAnswer:answer,msg:msg))]):Column(children:[Expanded(child:Field(defs:defs,foes:foes,onCell:place)),SizedBox(height:330,child:Quiz(q:q,onAnswer:answer,msg:msg))]))]);})));}
}
class Start extends StatelessWidget{final VoidCallback onStart;final String msg;const Start({super.key,required this.onStart,required this.msg});@override Widget build(BuildContext c)=>Scaffold(body:Container(decoration:const BoxDecoration(gradient:RadialGradient(center:Alignment.topCenter,radius:1.2,colors:[Color(0xff31562b),Color(0xff07110c)])),child:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[Container(width:105,height:105,decoration:BoxDecoration(color:const Color(0xffb8f34b),borderRadius:BorderRadius.circular(28)),child:const Center(child:Text('Σ',style:TextStyle(fontSize:62,fontWeight:FontWeight.w900,color:Color(0xff102018))))),const SizedBox(height:20),const Text('MATEMÁTICAS',style:TextStyle(fontSize:42,fontWeight:FontWeight.w900)),const Text('VS. ZOMBIS',style:TextStyle(fontSize:42,fontWeight:FontWeight.w900,color:Color(0xffb8f34b))),const SizedBox(height:14),const SizedBox(width:600,child:Text('Defiende Riobamba con estrategia. Resuelve retos, genera energía y coloca defensas lógicas antes de cada oleada.',textAlign:TextAlign.center,style:TextStyle(fontSize:18,height:1.5))),const SizedBox(height:24),FilledButton.icon(style:FilledButton.styleFrom(backgroundColor:const Color(0xffb8f34b),foregroundColor:const Color(0xff102018),padding:const EdgeInsets.all(20)),onPressed:onStart,icon:const Icon(Icons.play_arrow),label:const Text('INICIAR CAMPAÑA',style:TextStyle(fontWeight:FontWeight.w900))),if(msg.isNotEmpty)Padding(padding:const EdgeInsets.all(14),child:Text(msg)),const Wrap(spacing:10,children:[Chip(label:Text('5 misiones')),Chip(label:Text('15 temas')),Chip(label:Text('Sin internet')),Chip(label:Text('Estrategia'))])])))));}
class Bar extends StatelessWidget{final int mission,wave,energy,score,lives;final bool paused;final VoidCallback onPause;const Bar({super.key,required this.mission,required this.wave,required this.energy,required this.score,required this.lives,required this.paused,required this.onPause});@override Widget build(BuildContext c)=>Container(height:70,padding:const EdgeInsets.symmetric(horizontal:14),color:const Color(0xff0d1d14),child:Row(children:[Expanded(child:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.start,children:[Text('MISIÓN '+(mission+1).toString()+' · OLEADA '+wave.toString(),style:const TextStyle(fontSize:11,color:Color(0xff9bb09f))),Text(_GameState.missions[min(mission,4)],style:const TextStyle(fontWeight:FontWeight.w800))])),Stat(Icons.bolt,energy,const Color(0xffffd45c)),Stat(Icons.favorite,lives,const Color(0xffff6b62)),Stat(Icons.stars,score,const Color(0xffb8f34b)),IconButton(onPressed:onPause,icon:Icon(paused?Icons.play_arrow:Icons.pause))]));}
class Stat extends StatelessWidget{final IconData icon;final int n;final Color color;const Stat(this.icon,this.n,this.color,{super.key});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.symmetric(horizontal:6),child:Row(children:[Icon(icon,color:color,size:19),Text(n.toString(),style:const TextStyle(fontWeight:FontWeight.w900))]));}
class Field extends StatelessWidget{
 final List<Defender> defs;final List<Enemy> foes;final void Function(int,int) onCell;
 const Field({super.key,required this.defs,required this.foes,required this.onCell});
 @override Widget build(BuildContext c){
  final grid=Column(children:List.generate(5,(r)=>Expanded(child:Row(children:List.generate(7,(col)=>Expanded(child:InkWell(onTap:()=>onCell(r,col),child:Container(decoration:BoxDecoration(color:(r+col).isEven?const Color(0x1839a84a):const Color(0x181f7c37),border:Border.all(color:const Color(0x183fffff))),child:Center(child:Text(col<5?'+':'',style:const TextStyle(color:Color(0x5579d936),fontSize:24)))))))))));
  final defenseViews=defs.map((d)=>Align(alignment:Alignment(-1+(d.col+.5)*2/7,-1+(d.row+.5)*2/5),child:FractionallySizedBox(widthFactor:1/7,heightFactor:1/5,child:Container(margin:const EdgeInsets.all(4),decoration:BoxDecoration(color:const Color(0xffb8f34b),borderRadius:BorderRadius.circular(13)),child:const Icon(Icons.calculate,color:Color(0xff102018),size:32)))));
  final enemyViews=foes.map((e)=>Align(alignment:Alignment(-1+(e.col+.5)*2/7,-1+(e.row+.5)*2/5),child:FractionallySizedBox(widthFactor:1/7,heightFactor:1/5,child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[const Text('🧟',style:TextStyle(fontSize:36)),Text('❤'+e.hp.toString(),style:const TextStyle(fontSize:10,color:Color(0xffff8b83)))]))));
  return Container(margin:const EdgeInsets.all(12),decoration:BoxDecoration(borderRadius:BorderRadius.circular(18),gradient:const LinearGradient(colors:[Color(0xff244b2b),Color(0xff102417)]),border:Border.all(color:const Color(0xff47633d),width:2)),clipBehavior:Clip.antiAlias,child:Stack(children:[grid,...defenseViews,...enemyViews]));
 }
}
class Quiz extends StatefulWidget{final Q q;final void Function(String) onAnswer;final String msg;const Quiz({super.key,required this.q,required this.onAnswer,required this.msg});@override State<Quiz> createState()=>_QuizState();}
class _QuizState extends State<Quiz>{bool hint=false;@override void didUpdateWidget(covariant Quiz old){super.didUpdateWidget(old);if(old.q!=widget.q)hint=false;}@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(15),color:const Color(0xff0c1912),child:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Chip(backgroundColor:const Color(0xffb8f34b),label:Text(widget.q.topic,style:const TextStyle(color:Color(0xff102018),fontWeight:FontWeight.w900))),const SizedBox(height:6),Text(widget.q.text,style:const TextStyle(fontSize:19,fontWeight:FontWeight.w800,height:1.3)),const SizedBox(height:12),GridView.count(crossAxisCount:2,mainAxisSpacing:8,crossAxisSpacing:8,childAspectRatio:2.4,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),children:widget.q.options.map((x)=>OutlinedButton(onPressed:()=>widget.onAnswer(x),child:Text(x,style:const TextStyle(fontWeight:FontWeight.w800)))).toList()),TextButton.icon(onPressed:()=>setState(()=>hint=!hint),icon:const Icon(Icons.lightbulb,color:Color(0xffffd45c)),label:Text(hint?widget.q.hint:'Necesito una pista')),if(widget.msg.isNotEmpty)Container(width:double.infinity,padding:const EdgeInsets.all(9),color:const Color(0xff1b3022),child:Text(widget.msg,style:const TextStyle(fontSize:12))) ])));}
class Victory extends StatelessWidget{final int score;final VoidCallback onRestart;const Victory({super.key,required this.score,required this.onRestart});@override Widget build(BuildContext c)=>Scaffold(body:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('🏆',style:TextStyle(fontSize:84)),const Text('¡RIOBAMBA ESTÁ A SALVO!',style:TextStyle(fontSize:32,fontWeight:FontWeight.w900,color:Color(0xffb8f34b))),Text(score.toString()+' puntos estratégicos'),const SizedBox(height:22),FilledButton(onPressed:onRestart,child:const Text('Jugar nuevamente'))])));}
