import {CURRICULUM_WORLDS} from './core/curriculum_map_7egb.js';
const $=s=>document.querySelector(s), screens=[...document.querySelectorAll('.screen')];let stars=0,lives=5,q=0,enemy=100,locked=false;
const questions=[{q:'¿Cuál es el siguiente término? 2, 5, 8, 11, 14, …',a:17,o:[16,17,18,15],tip:'La sucesión aumenta de 3 en 3.'},{q:'48 ÷ 6 = ?',a:8,o:[6,7,8,9],tip:'Dividir 48 en 6 partes iguales da 8.'},{q:'125 + 378 = ?',a:503,o:[493,503,513,523],tip:'Suma unidades, decenas y centenas respetando el valor posicional.'},{q:'900 − 457 = ?',a:443,o:[433,443,453,457],tip:'Resta por valor posicional y comprueba sumando 457.'},{q:'7 × 8 = ?',a:56,o:[48,54,56,64],tip:'7 grupos de 8 forman 56.'},{q:'360 ÷ 10 = ?',a:36,o:[3.6,36,360,3600],tip:'Al dividir un natural por 10, el valor queda diez veces menor.'},{q:'Múltiplo de 6:',a:42,o:[35,40,42,45],tip:'42 = 6 × 7.'},{q:'¿Cuál es primo?',a:29,o:[21,27,29,33],tip:'29 solo tiene dos divisores: 1 y 29.'},{q:'5² = ?',a:25,o:[10,15,20,25],tip:'5² significa 5 × 5.'},{q:'√81 = ?',a:9,o:[7,8,9,10],tip:'9 × 9 = 81.'}];
function show(id){screens.forEach(s=>s.classList.toggle('active',s.id===id))}
$('#start-btn').onclick=()=>{show('play-screen');renderWaiting()};$('#worlds-btn').onclick=()=>showWorlds();document.querySelector('.back').onclick=()=>show('start-screen');$('#progress-btn').onclick=()=>popup('MI PROGRESO','⭐ '+stars+' estrellas<br>Retos superados: '+q+'/10');$('#settings-btn').onclick=()=>popup('CONFIGURACIÓN','Controles: flechas para desplazarte y ESPACIO para atacar.<br>Diseño optimizado para equipos escolares.');
function showWorlds(){show('world-screen');const g=$('#world-grid');g.innerHTML='';Object.values(CURRICULUM_WORLDS).slice(0,5).forEach((w,i)=>{const c=document.createElement('article');c.className='world-card '+(i&&stars<60?'locked':'');c.innerHTML='<h3>Mundo '+(i+1)+'</h3><h3>'+w.title+'</h3><p>'+(i?'🔒 Bloqueado':'✅ Disponible')+'</p><div class="stars">⭐ '+(i?0:stars)+'/60</div>';g.append(c)})}
function renderWaiting(){$('#activity-content').innerHTML='<div class="waiting"><div><div style="font-size:58px">⚔️</div><b>EXPLORA Y COMBATE</b><p>Muévete con ← → y presiona <b>ESPACIO</b><br>para activar el siguiente reto matemático.</p><p>Reto '+Math.min(q+1,10)+'/10 · ⭐ '+stars+'/60</p></div></div>'}
function challenge(){if(locked||q>=10)return;locked=true;const x=questions[q];$('#activity-content').innerHTML='<div class="question-card"><div class="counter">Mundo 1 · Pregunta '+(q+1)+'/10</div><h2>RETO MATEMÁTICO</h2><div class="question">'+x.q+'</div><div class="answers">'+x.o.map((v,i)=>'<button data-v="'+v+'">'+String.fromCharCode(65+i)+'.　'+v+'</button>').join('')+'</div><div class="feedback">💡 Selecciona una respuesta. Acierto: <b>+10 ⭐</b> · Error: <b>−2 ⭐</b>.</div></div>';document.querySelectorAll('.answers button').forEach(b=>b.onclick=()=>answer(+b.dataset.v,x))}
function answer(v,x){const ok=v===x.a;if(ok){stars+=10;enemy=Math.max(0,enemy-34);$('#hero').classList.add('attack');setTimeout(()=>$('#hero').classList.remove('attack'),500)}else{stars=Math.max(0,stars-2);lives=Math.max(0,lives-1)}q++;$('#enemy-hp span').style.width=enemy+'%';updateHud();const fb=$('.feedback');fb.innerHTML=ok?'<b class="good">✅ ¡CORRECTO! +10 ⭐</b><br>'+x.tip:'<b class="bad">❌ AÚN NO. −2 ⭐</b><br>Respuesta correcta: <b>'+x.a+'</b>.<br>'+x.tip;document.querySelectorAll('.answers button').forEach(b=>b.disabled=true);setTimeout(()=>{locked=false;if(q>=10)finish();else renderWaiting()},1800)}
function finish(){const score=Math.min(10,Math.round(stars/10));popup(score>=7?'¡MUNDO COMPLETADO!':'MISIÓN DE REFUERZO','Resultado: <b>'+score+'/10</b><br>⭐ '+stars+' estrellas<br>'+(score>=7?'Evaluación habilitada. Has demostrado dominio de los retos iniciales.':'Necesitas al menos 7/10. Puedes reintentar los retos.'));$('#eval-status').textContent='🏆 Evaluación: '+(score>=7?'habilitada':'requiere refuerzo')}
function updateHud(){$('#hud').textContent='❤️'.repeat(lives)+'　⭐ '+stars+'　Mundo 1';$('#global-progress').textContent='Progreso ⭐ '+stars+'/60'}
function popup(title,html){$('#modal-card').innerHTML='<h2>'+title+'</h2><p>'+html+'</p><button id="close-modal">CONTINUAR</button>';$('#modal').classList.remove('hidden');$('#close-modal').onclick=()=>$('#modal').classList.add('hidden')}
let heroX=18;addEventListener('keydown',e=>{if(!$('#play-screen').classList.contains('active')||locked)return;if(e.code==='ArrowRight')heroX=Math.min(46,heroX+4);if(e.code==='ArrowLeft')heroX=Math.max(8,heroX-4);$('#hero').style.left=heroX+'%';if(e.code==='Space'){e.preventDefault();challenge()}if(['KeyN','KeyM','KeyB'].includes(e.code)){e.preventDefault();$('#hero').classList.add('attack');setTimeout(()=>$('#hero').classList.remove('attack'),450)}});document.querySelectorAll('#skills button').forEach(b=>b.onclick=()=>{const code=b.dataset.key;if(code==='Space')challenge();else{$('#hero').classList.add('attack');setTimeout(()=>$('#hero').classList.remove('attack'),450)}});renderWaiting();