import {SpriteEngine,GameCharacter,CHARACTER_ASSETS} from './engine/sprite_engine.js';
import {CURRICULUM_WORLDS} from './core/curriculum_map_7egb.js';
const $=s=>document.querySelector(s),screens=[...document.querySelectorAll('.screen')];
const questions=[{q:'¿Cuál es el siguiente término? 2, 5, 8, 11, 14, …',a:17,o:[16,17,18,15],tip:'Aumenta de 3 en 3.'},{q:'48 ÷ 6 = ?',a:8,o:[6,7,8,9],tip:'48 dividido para 6 es 8.'},{q:'125 + 378 = ?',a:503,o:[493,503,513,523],tip:'Suma por valor posicional.'},{q:'900 − 457 = ?',a:443,o:[433,443,453,457],tip:'Comprueba sumando 457.'},{q:'7 × 8 = ?',a:56,o:[48,54,56,64],tip:'7 grupos de 8 forman 56.'},{q:'360 ÷ 10 = ?',a:36,o:[3.6,36,360,3600],tip:'Es diez veces menor.'},{q:'Múltiplo de 6:',a:42,o:[35,40,42,45],tip:'42 = 6 × 7.'},{q:'¿Cuál es primo?',a:29,o:[21,27,29,33],tip:'29 solo tiene divisores 1 y 29.'},{q:'5² = ?',a:25,o:[10,15,20,25],tip:'5 × 5 = 25.'},{q:'√81 = ?',a:9,o:[7,8,9,10],tip:'9 × 9 = 81.'}];
let stars=0,heroHP=100,enemyHP=100,heroHits=0,enemyHits=0,phase='battle',q=0,correct=0,locked=false,enemyTimer=null;
const canvas=$('#gameCanvas'),engine=new SpriteEngine(canvas);
const hero=engine.add(new GameCharacter(engine.ctx,CHARACTER_ASSETS.hero,80,70,220,270));
const demon=engine.add(new GameCharacter(engine.ctx,CHARACTER_ASSETS.demonBasic,620,65,220,280));engine.start();
window.addEventListener('asset:error',e=>{const w=$('#asset-warning');w.classList.remove('hidden');w.textContent='⚠ Falta '+e.detail.src+'. Instala este recurso gráfico; no se usará una figura geométrica.'});
function show(id){screens.forEach(s=>s.classList.toggle('active',s.id===id))}
function hpUI(){const h=$('#hero-hp i'),d=$('#enemy-hp i');if(h)h.style.width=heroHP+'%';if(d)d.style.width=enemyHP+'%';$('#hero-hp em').textContent=Math.round(heroHP)+'%';$('#enemy-hp em').textContent=Math.round(enemyHP)+'%';$('#hud').textContent='❤️ '+Math.round(heroHP)+'%　⭐ '+stars+'　Mundo 1'}
function msg(t){$('#battle-message').textContent=t}
function startBattle(){phase='battle';$('#activity-panel').classList.add('hidden');$('#game-panel').classList.remove('hidden');enemyHP=100;heroHits=0;enemyHits=0;hpUI();msg('⚔️ Derrota al enemigo: 12 golpes. ¡Defiéndete de sus ataques!');clearInterval(enemyTimer);enemyTimer=setInterval(enemyAttack,1150)}
function playerAttack(){if(phase!=='battle'||locked)return;heroHits++;enemyHP=Math.max(0,100-(heroHits/12)*100);hero.x+=18;setTimeout(()=>hero.x-=18,170);hpUI();if(enemyHP<=0){clearInterval(enemyTimer);phase='education';msg('🏆 Enemigo derrotado en '+heroHits+' golpes. Ahora recupera vida con Matemáticas.');setTimeout(startEducation,900)}}
function enemyAttack(){if(phase!=='battle'||enemyHP<=0)return;enemyHits++;heroHP=Math.max(0,heroHP-(100/14));hpUI();msg('💥 El enemigo golpeó '+enemyHits+'/14 · Vida '+Math.round(heroHP)+'%');if(heroHP<=0){clearInterval(enemyTimer);phase='revive';setTimeout(()=>startEducation(true),650)}}
function startEducation(revive=false){phase=revive?'revive':'education';$('#game-panel').classList.add('hidden');$('#activity-panel').classList.remove('hidden');q=0;correct=0;renderQuestion(revive)}
function renderQuestion(revive=phase==='revive'){const x=questions[q%questions.length];$('#activity-content').innerHTML='<div class="question-card"><div class="counter">'+(revive?'RECUPERACIÓN DE VIDA':'ENTRENAMIENTO')+' · Pregunta '+(q+1)+'/10</div><h2>'+ (revive?'❤️ RECUPERA TU VIDA':'📚 RETO MATEMÁTICO')+'</h2><div class="question">'+x.q+'</div><div class="answers">'+x.o.map((v,i)=>'<button data-v="'+v+'">'+String.fromCharCode(65+i)+'.　'+v+'</button>').join('')+'</div><div class="feedback">Correcta: <b>+10% de vida</b>. Con 7 correctas puedes volver al combate con hasta <b>80%</b>; con 10 correctas recuperas <b>100%</b>.</div><div class="edu-actions"><button id="fight-now" '+(correct<7?'disabled':'')+'>⚔️ VOLVER A PELEAR</button><span>Aciertos: <b>'+correct+'/10</b> · Vida: <b>'+Math.round(heroHP)+'%</b></span></div></div>';document.querySelectorAll('.answers button').forEach(b=>b.onclick=()=>answer(+b.dataset.v,x))}
function answer(v,x){if(locked)return;locked=true;const ok=v===x.a;if(ok){correct++;stars+=10;heroHP=Math.min(100,heroHP+10)}else stars=Math.max(0,stars-2);q++;hpUI();const fb=$('.feedback');fb.innerHTML=ok?'<b class="good">✅ Correcto. Vida +10%.</b> '+x.tip:'<b class="bad">❌ Intenta aprender de este error.</b> Respuesta: '+x.a+'. '+x.tip;document.querySelectorAll('.answers button').forEach(b=>b.disabled=true);const fight=$('#fight-now');if(fight){fight.disabled=correct<7;fight.onclick=()=>resumeBattle()}setTimeout(()=>{locked=false;if(q>=10)finishRecovery();else renderQuestion()},1000)}
function finishRecovery(){if(correct===10)heroHP=100;else if(correct>=7)heroHP=Math.max(heroHP,80);hpUI();if(correct>=7){popup('RECUPERACIÓN COMPLETADA','Aciertos: <b>'+correct+'/10</b><br>Vida: <b>'+Math.round(heroHP)+'%</b><br>Puedes volver a pelear o seguir recuperándote.','⚔️ PELEAR',resumeBattle)}else popup('SIGUE ENTRENANDO','Aciertos: <b>'+correct+'/10</b>. Necesitas al menos 7 correctas para volver al combate.','🔁 REINTENTAR',()=>startEducation(true))}
function resumeBattle(){closeModal();enemyHP=100;heroHits=0;enemyHits=0;startBattle()}
function popup(title,html,label='CONTINUAR',action=closeModal){$('#modal-card').innerHTML='<h2>'+title+'</h2><p>'+html+'</p><button id="close-modal">'+label+'</button>';$('#modal').classList.remove('hidden');$('#close-modal').onclick=action}
function closeModal(){$('#modal').classList.add('hidden')}
$('#start-btn').onclick=()=>{show('play-screen');startBattle()};$('#worlds-btn').onclick=()=>showWorlds();document.querySelector('.back').onclick=()=>show('start-screen');$('#progress-btn').onclick=()=>popup('MI PROGRESO','⭐ '+stars+' estrellas · Vida '+Math.round(heroHP)+'%');$('#settings-btn').onclick=()=>popup('CONFIGURACIÓN','Combate con ESPACIO, N, M o B. El enemigo necesita 14 golpes para derrotarte.');
function showWorlds(){show('world-screen');const g=$('#world-grid');g.innerHTML='';Object.values(CURRICULUM_WORLDS).slice(0,5).forEach((w,i)=>{const c=document.createElement('article');c.className='world-card '+(i&&stars<60?'locked':'');c.innerHTML='<h3>Mundo '+(i+1)+'</h3><h3>'+w.title+'</h3><div class="stars">⭐ '+(i?0:stars)+'/60</div>';g.append(c)})}
addEventListener('keydown',e=>{if(!$('#play-screen').classList.contains('active'))return;if(['Space','KeyN','KeyM','KeyB'].includes(e.code)){e.preventDefault();playerAttack()}});
document.querySelectorAll('#skills button').forEach(b=>b.onclick=playerAttack);hpUI();