import * as THREE from '../node_modules/three/build/three.module.js';
import {CURRICULUM_WORLDS} from './core/curriculum_map_7egb.js';
const canvas=document.querySelector('#game-canvas'),panel=document.querySelector('#activity-panel'),content=document.querySelector('#activity-content'),hud=document.querySelector('#hud');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.3));
const scene=new THREE.Scene();scene.background=new THREE.Color(0x030713);scene.fog=new THREE.FogExp2(0x07111b,.018);
const camera=new THREE.PerspectiveCamera(60,1,.1,150);camera.position.set(0,5,10);camera.lookAt(0,1,-8);
scene.add(new THREE.HemisphereLight(0x8bdcff,0x170a20,1.1));const moon=new THREE.DirectionalLight(0xb9d7ff,2);moon.position.set(-8,15,6);scene.add(moon);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(50,100),new THREE.MeshStandardMaterial({color:0x102319,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.z=-25;scene.add(ground);
for(let i=0;i<45;i++){const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.12,.2,3+Math.random()*3,6),new THREE.MeshStandardMaterial({color:0x291b16}));trunk.position.set((Math.random()-.5)*24,1.5,-Math.random()*70);scene.add(trunk);const crown=new THREE.Mesh(new THREE.ConeGeometry(1+Math.random(),3,7),new THREE.MeshStandardMaterial({color:0x123b2a}));crown.position.set(trunk.position.x,4,trunk.position.z);scene.add(crown)}
const hero=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(.45,1.2,4,8),new THREE.MeshStandardMaterial({color:0x173f36}));body.position.y=1.2;hero.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.38,12,8),new THREE.MeshStandardMaterial({color:0xf0c5a5}));head.position.y=2.35;hero.add(head);const sword=new THREE.Mesh(new THREE.BoxGeometry(.08,.08,2.2),new THREE.MeshStandardMaterial({color:0x8eeaff,emissive:0x007799,emissiveIntensity:2}));sword.position.set(.65,1.3,0);sword.rotation.z=-.55;hero.add(sword);hero.position.set(0,0,1);scene.add(hero);
const demons=[];for(let i=0;i<7;i++){const d=new THREE.Mesh(new THREE.CapsuleGeometry(.5,1.1,3,7),new THREE.MeshStandardMaterial({color:[0x6b1c35,0x40205c,0x7a2b18][i%3],roughness:.8}));d.position.set((Math.random()-.5)*14,.95,-8-i*8);d.userData.hit=false;scene.add(d);demons.push(d)}
let stars=0,lives=5,active=false,qIndex=0;const qs=[['36 ÷ 6 = ?',6,[5,6,7,8]],['8 × 7 = ?',56,[48,54,56,64]],['120 ÷ 10 = ?',12,[10,11,12,20]],['25 + 38 = ?',63,[53,61,63,73]],['90 - 47 = ?',43,[33,43,47,53]],['3 × (8 + 2) = ?',30,[24,28,30,32]]];
function challenge(){active=true;panel.className='panel activity-active';const [q,a,opts]=qs[qIndex++%qs.length];content.innerHTML='<div class="card"><h2>⚔ RETO MATEMÁTICO</h2><div class="question">'+q+'</div><div class="answers">'+opts.map(x=>'<button data-v="'+x+'">'+x+'</button>').join('')+'</div><div class="feedback">Selecciona la respuesta correcta. Cada acierto suma 10 ⭐; un error resta 2 ⭐.</div></div>';content.querySelectorAll('button').forEach(b=>b.onclick=()=>{const ok=+b.dataset.v===a;stars=Math.max(0,stars+(ok?10:-2));content.querySelector('.feedback').textContent=ok?'✅ Correcto. Identificaste la operación y verificaste el resultado. ¡Continúa!':'🔎 Revisa el procedimiento: identifica la operación, resuelve paso a paso y comprueba el resultado.';hud.textContent='⭐ '+stars+' · ❤️ '+lives+' · Mundo 1';setTimeout(()=>{active=false;panel.className='panel activity-waiting';content.innerHTML='<p class="waiting-message">🎮 Continúa explorando para encontrar otro reto...</p>'},1700)})}
const keys=new Set();addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='Space'&&!active){e.preventDefault();const near=demons.find(d=>!d.userData.hit&&d.position.distanceTo(hero.position)<4);if(near){near.userData.hit=true;near.visible=false;challenge()}}});addEventListener('keyup',e=>keys.delete(e.code));
const clock=new THREE.Clock();function resize(){const w=canvas.clientWidth,h=canvas.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}function loop(){requestAnimationFrame(loop);resize();const dt=Math.min(clock.getDelta(),.05);if(!active){const s=5*dt;if(keys.has('ArrowLeft'))hero.position.x-=s;if(keys.has('ArrowRight'))hero.position.x+=s;if(keys.has('ArrowUp'))hero.position.z-=s;if(keys.has('ArrowDown'))hero.position.z+=s;hero.position.x=THREE.MathUtils.clamp(hero.position.x,-9,9);hero.position.z=THREE.MathUtils.clamp(hero.position.z,-60,4)}camera.position.x+=(hero.position.x-camera.position.x)*.06;camera.position.z+=(hero.position.z+10-camera.position.z)*.06;camera.lookAt(hero.position.x,1.3,hero.position.z-5);renderer.render(scene,camera)}loop();